language: go

arch: amd64

os:
  - windows
  - linux
  - osx

go:
  - 1.15.x

before_install:
  - go get -t -v ./...
  - go vet ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)